### ISSUE TITLE
Formato richiesta non corretto

### ISSUE THREAD

**Issue by faina09** [DotNetCodeIT/spid-dotnet-sdk#2]
eseguendo SPID_ASPNET_CORE_2_0_NoIdentity il sito https://spidposte.test.poste.it/jod-fs/ssoservicepost risponde:
```

Attenzione: si è verificato un errore

Formato richiesta non corretto - Contattare il gestore del servizio
```

**Comment by BuonoPaolo** [comment]
Identico problema ...

**Comment by congiuluc** [comment]
Il problema è dovuto ai certificati dell'ambiente di test di Poste
